### ISSUE TITLE
deps.edn classifier syntax change

### ISSUE THREAD

**Issue by puredanger** [lxbr/effing#1]
Hi, I wanted to let you know that the syntax for classifiers in deps.edn files has changed with the latest release (1.10.0.408). The classifier attribute is no longer used and instead the classifier is added to the lib name itself as groupId/artifactId$classifier.

In your deps.edn, you might want to switch to the next syntax like:

```
com.github.jnr/jffi {:mvn/version "1.2.17"}
com.github.jnr/jffi$native {:mvn/version "1.2.17"}
``` 

If you have any issues, feel free to file a ticket at https://dev.clojure.org/jira/browse/TDEPS for tools.deps.alpha.

**Comment by lxbr** [comment]
@puredanger Thank you! The new syntax looks reasonable.

Although the empty string for _no classifier_ looked strange, the real issue for me was only having a single deps entry for the default dependency. One deps entry per artifact+classifier is certainly cleaner.

Well done!
